### ISSUE TITLE
Incorrect "Build failing" status in the README

### ISSUE THREAD

**Issue by dandv** [mondora/ddp.js#8]
I currently see "Build failing" but https://travis-ci.org/mondora/ddp.js passes.

**Comment by pscanf** [comment]
Yeah, the other day when I version-bumped to 1.0.0 the build was failing due to some coveralls issue. I'm working on [queueing](https://github.com/mondora/ddp.js/tree/queueing) now, which passed the build (probably because I updated the coveralls dependency). I expect the badge to change when I merge to master later today. :smiley:

**Comment by pscanf** [comment]
Actually, I restarted the failed builds on travis and now they seem to pass. It might have been coveralls was down or something. The badge got fixed now. :smiley:
